[project]
name = "cambalache"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.2.3",
    "typer[all]>=0.15.2",
]

[dependency-groups]
dev = [
    "ruff>=0.11.7",
]
